# Generated by Django 4.2.3 on 2023-07-14 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_roomprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_option',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=50),
        ),
    ]
