# Generated by Django 4.2.3 on 2023-07-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashbaoard", "0002_alter_accommodation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="image",
            field=models.ImageField(upload_to="product_files/"),
        ),
    ]
